version: '3.1'

networks:
  nat:
    external: true
  internal:
    external: false
  thxnet:
    external: true

services:
  thinx-api:
    privileged: true # because of DIND builders
    shm_size: 256M
    networks:
      - nat # for Device access
      - internal # for Console access
      - thxnet
    env_file: ./.env
    environment:
      - THINX_HOSTNAME=${THINX_HOSTNAME}
      - THINX_OWNER_EMAIL=${THINX_OWNER_EMAIL}
      - REVISION=${REVISION}
      - ROLLBAR_ACCESS_TOKEN=${ROLLBAR_ACCESS_TOKEN}
      - ROLLBAR_ENVIRONMENT=${ROLLBAR_ENVIRONMENT}
      #- SQREEN_TOKEN=${SQREEN_TOKEN} # (optional, free for open-source)
    build: . # suculent/thinx-device-api
    ports:
#      - 7441:7441 # Reserved for Web HTTPS, 7440 is Web HTTP
      - 7442:7442 # API (HTTP)
      - 7443:7443 # API (HTTPS)
      - 7444:7444 # WebSocket
      - 7445:7445 # WebSocket SSL (reserved)
      - 9002:9002 # Incoming GIT (User) Webhooks; will deprecate
    volumes:
      - /mnt/data/deploy:/mnt/data/deploy # Deployment
      - /mnt/data/mosquitto/auth:/mnt/data/mosquitto # Authentication
      - /mnt/data/repos:/mnt/data/repos # Git
      - /mnt/data/ssl:/mnt/data/ssl
      - /var/run/docker.sock:/var/run/docker.sock # DIND
      - /var/lib/doocker
      - /cache
    labels:
      - "traefik.docker.network=nat"
      - "traefik.enable=true"
      - "traefik.port=7442"
      - "traefik.backend=thinx-api"
      - "traefik.frontend.rule=Host:${THINX_HOSTNAME}"

 # dind:
 #   privileged: true # because of DIND builders
 #   image: docker:dind
 #   volumes:
 #     - /var/run/docker.sock:/var/run/docker.sock # DIND
 #     - /cache
