version: '2.2'

networks:
  nat:
    external: true
  internal:
    external: false

services:

  mosquitto:
    env_file: .env
    # image: suculent/thinx-message_broker
    build: ./services/broker
    ports:
      - "1883:1883" # Must be exposed to devices
      - "8883:8883" # Must be exposed to devices
    restart: unless-stopped
    networks:
      - nat
      - internal
    volumes:
      - /mnt/data/mosquitto/config:/mqtt/config:rw
      - /mnt/data/mosquitto/data:/mqtt/data:rw
      - /mnt/data/mosquitto/log:/mqtt/log:rw
      - /mnt/data/mosquitto/ssl:/mqtt/ssl:rw
      - /mnt/data/mosquitto/auth:/mqtt/auth:rw
    labels:
     - "traefik.backend.mosquitto.noexpose"

  couchdb:
    env_file: .env
    image: apache/couchdb:2.3.1
    # build: ./services/couchdb # currently unused for speed, should work the same except it does not log pass in entry point
    restart: always
    environment:
      - NODENAME=${NODENAME}
      - COUCHDB_USER=${COUCHDB_ADMIN}
      - COUCHDB_PASSWORD=${COUCHDB_PASS}
      - COUCHDB_COOKIE=${COUCHDB_COOKIE}
      - COUCHDB_SECRET=${COUCHDB_SECRET}
    ports:
      - 5984
    networks:
      - nat
      - internal
    volumes:
      - /mnt/data/couchdb:/var/lib/couchdb
      - /mnt/data/couchdb:/opt/couchdb/data
    labels:
      - "traefik.backend.couchdb.noexpose"

  thinx-redis:
    env_file: .env
    networks:
      - internal
    # image: suculent/redis-slave:latest
    build:
      context: ./services/redis
      args:
        - ALLOW_EMPTY_PASSWORD=no
        - REDIS_PASSWORD=${REDIS_PASSWORD}
        - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--port", "6379"]
    environment:
      - ALLOW_EMPTY_PASSWORD=no
#      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    restart: always
    ports:
      - 6379
    volumes:
      - /mnt/data/redis:/data
    labels:
     - "traefik.backend.thinx-redis"

  transformer:
    env_file: .env
    user: transformer
    build:
      context: ./services/transformer
      args:
        - SQREEN_APP_NAME=${SQREEN_APP_NAME}
        - SQREEN_TOKEN=${SQREEN_TOKEN}
    restart: always
    environment:
      - SQREEN_APP_NAME=${SQREEN_APP_NAME}
      - SQREEN_TOKEN=${SQREEN_TOKEN}
    networks:
      - internal
    ports:
      - "7474"
    labels:
     - "traefik.backend.transformer.noexpose"

  thinx-api:
    # because of DIND builders
    privileged: true
    # reserve enough for builders
    shm_size: 2048M
    # tty: true
    restart: always
    depends_on:
      - transformer
      - thinx-redis
    networks:
      - nat
      - internal
    env_file: .env
    build:
      context: .
      args:
        - THINX_HOSTNAME=${THINX_HOSTNAME}
        - THINX_OWNER_EMAIL=${THINX_OWNER_EMAIL}
        - REVISION=${REVISION}
        - ROLLBAR_ACCESS_TOKEN=${ROLLBAR_ACCESS_TOKEN}
        - ROLLBAR_ENVIRONMENT=${ROLLBAR_ENVIRONMENT}
        - SQREEN_TOKEN=${SQREEN_TOKEN}
        - SQREEN_APP_NAME=${SQREEN_APP_NAME}
    environment:
      - THINX_HOSTNAME=${THINX_HOSTNAME}
      - THINX_OWNER_EMAIL=${THINX_OWNER_EMAIL}
      - REVISION=${REVISION}
      - ROLLBAR_ACCESS_TOKEN=${ROLLBAR_ACCESS_TOKEN}
      - ROLLBAR_ENVIRONMENT=${ROLLBAR_ENVIRONMENT}
      - SQREEN_TOKEN=${SQREEN_TOKEN}
      - SQREEN_APP_NAME=${SQREEN_APP_NAME}
    # image: suculent/thinx-device-api
    ports:
#      - 7441:7441 # Reserved for Web HTTPS, 7440 is Web HTTP
      - 7442:7442 # API (HTTP)
      - 7443:7443 # API (HTTPS)
      - 7444:7444 # WebSocket
      - 7445:7445 # WebSocket SSL (reserved)
      - 9002:9002 # Incoming GIT (User) Webhooks
    volumes:
      - /mnt/data/deploy:/mnt/data/deploy # Deployment
      - /mnt/data/mosquitto:/mnt/data/mosquitto # Authentication
      - /mnt/data/repos:/mnt/data/repos # Git
      - /mnt/data/ssl:/mnt/data/ssl
      - /mnt/data/ssh_keys:/mnt/data/ssh_keys
      - /var/run/docker.sock:/var/run/docker.sock # DIND
      - /var/lib/docker
      - /cache
    labels:
      - "traefik.docker.network=nat"
      - "traefik.enable=true"
      - "traefik.port=7442"
      - "traefik.backend=thinx-api"
      - "traefik.frontend.rule=Host:${THINX_HOSTNAME}"

  console:
    env_file:
      - .env
    #image: suculent/thinx-console
    build:
      context: ./services/console/src
      args:
       - NGINX_PORT=80
       - NGINX_HOST=${WEB_HOSTNAME}
       - WEB_HOSTNAME=${WEB_HOSTNAME}
       - API_HOSTNAME=${API_HOSTNAME}
       - API_BASEURL=${API_BASEURL}
       - ENTERPRISE=${ENTERPRISE}
       - ENVIRONMENT=${ENVIRONMENT}
       - GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID}
       - ROLLBAR_ACCESS_TOKEN=${ROLLBAR_ACCESS_TOKEN}
    networks:
      - nat
      - internal
    ports:
      - "80"
    restart: always
#    environment:
#     - NGINX_PORT=80
#     - NGINX_HOST=${WEB_HOSTNAME}
#     - WEB_HOSTNAME=${WEB_HOSTNAME}
#     - API_HOSTNAME=${API_HOSTNAME}
#     - API_BASEURL=${API_BASEURL}
#     - ENTERPRISE=${ENTERPRISE}
#     - ENVIRONMENT=${ENVIRONMENT}
#     - GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID}
#     - ROLLBAR_ACCESS_TOKEN=${ROLLBAR_ACCESS_TOKEN}

    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.backend=console"
      - "traefik.frontend.rule=Host:console.staging.thinx.cloud"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.SSLHost=console.staging.thinx.cloud"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
