networks:
  internal:
    external: false

version: '3'

networks:
  internal:
    external: false

services:
  transformer:
    user: transformer # or ${CURRENT_UID} if CURRENT_UID=$(id -u):$(id -g) docker-compose up
    image: suculent/thinx-node-transformer
    networks:
      - internal
    ports:
      - "7474:7474"
    networks: 
      - internal
    restart: always
    env_file: .env
    labels:
    - "traefik.backend.transformer.noexpose"

